export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpeg",
      username: "Nimai Halder",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpeg",
      username: "Sourish Mondal",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "Momota bannerjie",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Sunetra Maity",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Saikat Bar",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "Sneha Bar",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Arindam Pradhan",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Rani Das",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Rimpa Dolui",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "accets\gift.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "accets\gift.png",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "accets\gift.png",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "accets\gift.png",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "accets\gift.png",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "accets\gift.png",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "accets\gift.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "accets\gift.png",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "accets\gift.png",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "accets\gift.png",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];